### ISSUE TITLE
Not loading all the users from the system

### ISSUE THREAD

**Issue by Power-Maverick** [DynamicsNinja/InAppNotificationBuilder#1]
We have an instance where there are more than 5k users and does not load all users during Test in the user drop-down.

---
- Deployment: Online
- DB Version: 9.2.21112.140
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.9.52
- Tool Version: 1.2021.11.2

**Comment by DynamicsNinja** [comment]
Actually had the same problem yesterday when I was working on a new tool with a number of web resources 🤣 I will push the fix for this one soon
