### ISSUE TITLE
I want to add the column name and open that record in the notifications 

### ISSUE THREAD

**Issue by TanviMathkar** [DynamicsNinja/InAppNotificationBuilder#5]
[Write your comment/feedback/issue here]

---
- Deployment: Online
- DB Version: 9.2.23014.162
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2022.11.59
- Tool Version: 1.2022.4.2

**Comment by DynamicsNinja** [comment]
I'm not sure that I understand what you want to achieve here. Can you write more details for your use case?

**Comment by DynamicsNinja** [comment]
Closing issue since there is no additional feedback received.
